### ISSUE TITLE
Making the leader slower

### ISSUE THREAD

**Issue by Fourstroker** [tkem/openlap#109]
It would be cool, if there is a feature available which is reducing the speed of the leading car step by step automatically in the race, when this driver is getting too dominant. At the moment I do this by hand but it is not easy to change the tuning settings while driving.

**Comment by tkem** [comment]
@Fourstroker: Thanks for your input. However, I've decided to *not* implement any features that require adjusting speed or brake *automatically*. Depending on your control unit firmware version, this may lead to some weird effects, e.g. cars becoming unresponsive for a few seconds. Additionally, since there is no "feedback" from the car, failure to set the speed will go unnoticed, for example if a car is deslotted. I think most of these situations can be handled quite well when manually adjusting the values, but for automatic adjustments, this is all too quirky for me.
